### ISSUE TITLE
proposal: remove expand query parameter

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/api#10]
I think we should drop `expand`. (It's not supported right now anyway.) 

The [definition in our docs](https://api.moov.io/#tag/Customers) is: 

> Return nested objects rather than ID's in the response body.

I don't like returning different json bodies based on a query param. I don't know of any clients that can't handle fairly flat JSON and I assume those might be easier to speak to in custom protocols. 

cc @wadearnold Added the parameter originally.

**Comment by wadearnold** [comment]
I agree. Not sure how I wanted to return nested objects. I think that's why
graphQL was invented.
