### ISSUE TITLE
batches: add endpoint documentation

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/api#17]
There are endpoints in our `ach` service which allow modifying batches within an ACH file, but we haven't documented these. They may have been lost when I [consolidated our api docs together](https://github.com/moov-io/docs/issues/5). 

Here are the endpoints:  https://github.com/moov-io/ach/blob/master/server/routing.go#L157

Original ACH openapi.yml: https://github.com/moov-io/ach/blob/2f14a52651de18d4d7284093dc98cb7543645a3a/server/openapi.yaml

Current openapi yml: https://github.com/moov-io/api/blob/master/openapi.yaml

Found during https://github.com/moov-io/moov-io/issues/4

**Comment by adamdecaf** [comment]
cc @wadearnold

**Comment by adamdecaf** [comment]
For reference

```
$ curl -s -H "cookie: moov_auth=nice-try" https://api.moov.io/v1/ach/files | jq .
{
  "files": [
    {
      "id": "xbnwcxscvctbljxotdpb",
      "fileHeader": {
        "id": "xbnwcxscvctbljxotdpb",
        "immediateDestination": "231380104",
        "immediateOrigin": "121042882",
        "fileCreationDate": "2018-10-08T00:00:00Z",
        "fileCreationTime": "2018-10-08T00:00:00Z",
        "fileIDModifier": "A",
        "immediateDestinationName": "Federal Reserve Bank",
        "immediateOriginName": "My Bank Name"
      },
      "batches": [
        {
          "batchHeader": {
            "id": "xbnwcxscvctbljxotdpb",
            "serviceClassCode": 200,
            "companyName": "Your Company, Inc",
            "companyIdentification": "121042882",
            "standardEntryClassCode": "PPD",
            "companyEntryDescription": "Online Order",
            "effectiveEntryDate": "2018-10-09T00:00:00Z",
            "ODFIIdentification": "12104288",
            "batchNumber": 1
          },
          "entryDetails": [
            {
              "id": "xbnwcxscvctbljxotdpb",
              "transactionCode": 22,
              "RDFIIdentification": "23138010",
              "checkDigit": "4",
              "DFIAccountNumber": "81967038518      ",
              "amount": 100000,
              "identificationNumber": "#83738AB#      ",
              "individualName": "Steven Tander         ",
              "discretionaryData": "  ",
              "addendaRecordIndicator": 1,
              "traceNumber": 121042880000001,
              "category": "Forward"
            }
          ],
          "batchControl": {
            "id": "xbnwcxscvctbljxotdpb",
            "serviceClassCode": 200,
            "entryAddendaÇount": 0,
            "entryHash": 0,
            "totalDebit": 0,
            "totalCredit": 0,
            "companyIdentification": "121042882",
            "ODFIIdentification": "12104288",
            "batchNumber": 1
          }
        }
      ],
      "IATBatches": null,
      "fileControl": {
        "id": "",
        "batchCount": 1,
        "blockCount": 1,
        "entryAddendaCount": 0,
        "entryHash": 0,
        "totalDebit": 0,
        "totalCredit": 0
      },
      "NotificationOfChange": null,
      "ReturnEntries": null
    }
  ],
  "error": null
}
```

**Comment by rjseymour66** [comment]
Hello,

I am a professional technical writer looking to contribute to a project.  Do you still need help documenting these endpoints or any other areas?

Please let me know how I can help.

- Ryan

**Comment by juanchik** [comment]
Hi @adamdecaf 
I can also suggest my help. I am a newbie and would like to contribute and learn at the same time. 
Please let me know with what I can start.

Anton

**Comment by adamdecaf** [comment]
@rjseymour66 @juanchik 

Thanks for reaching out! We have some issues labeled ["help wanted"](https://github.com/search?q=org%3Amoov-io+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 ) and ["good first issue"](https://github.com/search?q=org%3Amoov-io+is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 ) that you could help out on! 

We host our API docs [on api.moov.io](https://api.moov.io/) and there are likely confusing wordings in there. Taking a read through would be much appreciated! 

Feel free to reach out on slack or issues with questions you have.

**Comment by juanchik** [comment]
Hi @adamdecaf, @rjseymour66 
I will start reading this weekend. And I will get in touch with you.

**Comment by adamdecaf** [comment]
There are some `TODO`'s littered in the file, but these are the next few we need to model. 

- File
   - NotificationOfChange
   - ReturnEntries
- Addendum records
- WEBDetail

**Comment by adamdecaf** [comment]
Specific issues have been created to address additional features. Closing this meta issue.
